begin;
grant usage on schema extensions to prelaunch_api;
select no_plan();
select ok(not has_table_privilege('prelaunch_api','auth.users','SELECT'),'association cannot read Auth accounts');
select ok(not has_table_privilege('prelaunch_api','registration_private.news_subscriptions','SELECT'),'association has no direct subscription-table privileges');
select ok(not has_function_privilege('authenticated','public.issue_account_signup_handoff(uuid,text,text)','EXECUTE'),'only account backend can issue a handoff');
insert into auth.users(id,email,raw_user_meta_data,created_at)
values('95000000-0000-4000-8000-000000000001','news@example.test',jsonb_build_object('display_name','News test','beta_age_eligible',true,
'beta_eligibility_year',extract(year from timezone('America/Toronto',now()))::int,'beta_eligibility_policy_version','brock-beta-eligibility-2026-10-06.1'),now());
select is((select count(*)::int from public.profiles where id='95000000-0000-4000-8000-000000000001'),1,'real account signup retains profile trigger');
select is((select count(*)::int from public.user_roles where user_id='95000000-0000-4000-8000-000000000001'),0,'public signup creates no admin role');
select is((select count(*)::int from registration_private.news_subscriptions),0,'account creation alone does not subscribe to email');
set local role service_role;
select lives_ok($$select public.issue_account_signup_handoff('95000000-0000-4000-8000-000000000001',' NEWS@EXAMPLE.TEST ',repeat('11',32))$$,'backend issues normalized identity-bound handoff');
reset role;
set local role prelaunch_api;
select is(registration_private.complete_account_signup(decode(repeat('11',32),'hex'),decode(repeat('22',32),'hex')),true,'one-time handoff becomes a host-only receipt');
select is(registration_private.complete_account_signup(decode(repeat('11',32),'hex'),decode(repeat('33',32),'hex')),false,'handoff replay is rejected');
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),'account','receipt permits thank-you page but no subscription');
select is(registration_private.account_receipt_status(decode(repeat('55',32),'hex')),null,'forged receipt cannot view thanks');
select is(registration_private.set_account_news_consent(decode(repeat('22',32),'hex'),true,'launch-sports-news-2026-10-09.1',decode(repeat('44',32),'hex')),true,'explicit optional consent is recorded');
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),'pending','unverified email cannot receive news');
reset role;
select is((select count(*)::int from registration_private.news_consent_events where purpose='launch_and_sports_news' and event='requested'),1,'versioned purpose-specific consent is persisted');
update auth.users set email_confirmed_at=now() where id='95000000-0000-4000-8000-000000000001';
set local role prelaunch_api;
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),'subscribed','existing Auth verification confirms pending news consent');
select is(registration_private.news_unsubscribe(decode(repeat('44',32),'hex'),false),true,'email scanner GET only validates withdrawal capability');
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),'subscribed','GET does not withdraw consent');
select is(registration_private.news_unsubscribe(decode(repeat('44',32),'hex'),true),true,'explicit unsubscribe suppresses news without account sign-in');
select is(registration_private.set_account_news_consent(decode(repeat('22',32),'hex'),true,'launch-sports-news-2026-10-09.1',decode(repeat('66',32),'hex')),false,'duplicate signup cannot undo withdrawal');
reset role;
select is((select count(*)::int from registration_private.news_consent_events where event='confirmed'),1,'verification evidence is durable');
select is((select count(*)::int from registration_private.registrations),0,'old development-only list is not repurposed');
update auth.users set email='new-news@example.test' where id='95000000-0000-4000-8000-000000000001';
set local role prelaunch_api;
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),'account','old-address withdrawal is not mistaken for new-address consent');
select is(registration_private.set_account_news_consent(decode(repeat('22',32),'hex'),true,'launch-sports-news-2026-10-09.1',decode(repeat('bb',32),'hex')),true,'new address requires a separate explicit choice');
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),'subscribed','receipt status selects only the current account email');
reset role;
select is((select state from registration_private.news_subscriptions where email='news@example.test'),'unsubscribed','new address does not restore old-address subscription');
update registration_private.account_signup_receipts set expires_at=now()-interval '1 second';
set local role prelaunch_api;
select is(registration_private.account_receipt_status(decode(repeat('22',32),'hex')),null,'expired receipt cannot view thanks');
select is(registration_private.set_account_news_consent(decode(repeat('22',32),'hex'),false,'test',decode(repeat('77',32),'hex')),false,'expired receipt cannot change preferences');
reset role;
set local role service_role;
select public.issue_account_signup_handoff('95000000-0000-4000-8000-000000000099','news@example.test',repeat('88',32));
reset role;
set local role prelaunch_api;
select is(registration_private.complete_account_signup(decode(repeat('88',32),'hex'),decode(repeat('99',32),'hex')),true,'obfuscated duplicate account receives generic confirmation');
select is(registration_private.account_receipt_status(decode(repeat('99',32),'hex')),'generic','duplicate reveals no account or subscription state');
select is(registration_private.set_account_news_consent(decode(repeat('99',32),'hex'),true,'test',decode(repeat('aa',32),'hex')),false,'generic duplicate cannot change another account consent');
reset role;
select * from finish();
rollback;
