-- Deliberately empty. Local development and deployed environments must use
-- reviewed source imports; the application never creates sample accounts,
-- leagues, athletes, schedules, scores, or standings.
